### ISSUE TITLE
Jest 26 does not handle the `default` import  (Jest: a transform must export a `process` function.)

### ISSUE THREAD

**Issue by fatso83** [anc95/jest-chain-transform#5]
After reading https://github.com/facebook/jest/issues/8725 I was about to write a transformer myself, when I came upon your module. Seemed like a godsend :smile: But after copying the setup code more or less exactly, I got an error:

```
 FAIL  code/Foo.test.jsx
  ● Test suite failed to run

    TypeError: Jest: a transform must export a `process` function.

      at ScriptTransformer._getTransformer (../node_modules/.pnpm/@jest+transform@26.6.2/node_modules/@jest/transform/build/ScriptTransformer.js:337:13)
      at ScriptTransformer.transformSource (../node_modules/.pnpm/@jest+transform@26.6.2/node_modules/@jest/transform/build/ScriptTransformer.js:390:28)
      at ScriptTransformer._transformAndBuildScript (../node_modules/.pnpm/@jest+transform@26.6.2/node_modules/@jest/transform/build/ScriptTransformer.js:516:40)
      at ScriptTransformer.transform (../node_modules/.pnpm/@jest+transform@26.6.2/node_modules/@jest/transform/build/ScriptTransformer.js:553:25)
```

I then added some `console.log` statements before the failing code to have a look at the object that did not have the required `process` function:
```

filepath to transform /home/foobar/tests/utils/setupTests.ts
transformPath /home/foobar/node_modules/.pnpm/jest-chain-transform@0.0.4/node_modules/jest-chain-transform/lib/index.js
{
  default: {
    canInstrument: true,
    getCacheKey: [Function: getCacheKey],
    process: [Function: process],
    getCacheKeyAsync: [Function: getCacheKeyAsync],
    processAsync: [Function: processAsync]
  }
}
```

OK, so the problem seems quite clear: the `require`d `jest-chain-transform` module is a transpiled ES Module, which only exports a `default` field. I tried manually patching the `module.exports` code by doing `Object.assign`, but that failed in the step after. So, if this is working, how have you setup Jest to handle the `default` imports and what should I do?

# Version info
-  Jest 26.6.3
- Node 17 and 14 (tried both)

# Jest config

<details>

```
module.exports = {
  rootDir: './code',
  clearMocks: true,
  moduleDirectories: ['node_modules', 'code/projA/src', 'code/projB/src'],
  transformIgnorePatterns: ['node_modules/(?!(@iconscout))/'],

  // https://jestjs.io/docs/code-transformation
  transform: {
    // see https://babeljs.io/docs/en/options to know what to stuff into this options object
    '\\.[jt]sx?$': [
      'jest-chain-transform',
      {
        transformers: [
          '../.jest/debug-transformer.js',
          {},
          'babel-jest',
          {
            targets: {
              esmodules: false,
            },
          },
        ],
      },
    ],
  },
  setupFilesAfterEnv: ['<rootDir>/projA/test/setup/pre-jest-init.js'],
  setupFilesAfterEnv: ['<rootDir>/projB/tests/utils/setupTests.ts', '<rootDir>/clinic/test/setup/jest-init.js'],
  reporters: [
    'default',
    [
      'jest-junit',
      {
        outputDirectory: '<rootDir>/../test-output/',
        suiteName: 'Nimble jest tests',
        ancestorSeparator: ' › ',
        suiteNameTemplate: '{filename}',
        classNameTemplate: '{classname}',
        titleTemplate: '{title}',
      },
    ],
  ],

}
```

</details>

**Comment by anc95** [comment]
@mhoffner  Is it ok for you to upgrade your jest to 27 version. Transformer written in ESM is supported after 27 https://github.com/facebook/jest/pull/11163

Meanwhile, you can clone this repo, and run `yarn && yarn test`, this will exec testcase under [src/example](https://github.com/anc95/jest-chain-transform/tree/main/src/example)
